//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acudiente
    {
        public acudiente()
        {
            this.alumno = new HashSet<alumno>();
        }
    
        public long Acu_ID { get; set; }
        public string Acu_Doc { get; set; }
        public string Acu_Nom { get; set; }
        public string Acu_Apel { get; set; }
        public string Acu_Tel { get; set; }
        public string Acu_Email { get; set; }
        public string Acu_Passw { get; set; }
        public System.DateTime Acu_FecReg { get; set; }
        public int Acu_Status { get; set; }
    
        public virtual ICollection<alumno> alumno { get; set; }
    }
}
