//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public long Adm_ID { get; set; }
        public string Adm_Doc { get; set; }
        public string Adm_Nom { get; set; }
        public string Adm_Apel { get; set; }
        public string Adm_Tel { get; set; }
        public string Adm_Email { get; set; }
        public string Adm_Passw { get; set; }
        public System.DateTime Adm_FecReg { get; set; }
        public int Adm_Status { get; set; }
    }
}
