//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public alumno()
        {
            this.alumno_clase = new HashSet<alumno_clase>();
        }
    
        public long Alum_ID { get; set; }
        public string Alum_Doc { get; set; }
        public string Alum_Nom { get; set; }
        public string Alum_Apel { get; set; }
        public string Alum_Tel { get; set; }
        public string Alum_Email { get; set; }
        public string Alum_Passw { get; set; }
        public System.DateTime Alum_FecReg { get; set; }
        public int Alum_Status { get; set; }
        public long Acu_ID { get; set; }
    
        public virtual acudiente acudiente { get; set; }
        public virtual ICollection<alumno_clase> alumno_clase { get; set; }
    }
}
