//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        public calificaciones()
        {
            this.alumno_clase = new HashSet<alumno_clase>();
        }
    
        public long Cal_ID { get; set; }
        public double Cal_N1 { get; set; }
        public double Cal_N2 { get; set; }
        public double Cal_N3 { get; set; }
        public double Cal_NF { get; set; }
    
        public virtual ICollection<alumno_clase> alumno_clase { get; set; }
    }
}
