//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dias
    {
        public dias()
        {
            this.horario = new HashSet<horario>();
        }
    
        public long Dia_ID { get; set; }
        public string Dia_Nom { get; set; }
    
        public virtual ICollection<horario> horario { get; set; }
    }
}
