//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docente
    {
        public docente()
        {
            this.clase = new HashSet<clase>();
        }
    
        public long Doc_ID { get; set; }
        public string Doc_Doc { get; set; }
        public string Doc_Nom { get; set; }
        public string Doc_Apel { get; set; }
        public string Doc_Tel { get; set; }
        public string Doc_Email { get; set; }
        public string Doc_Passw { get; set; }
        public System.DateTime Doc_FecReg { get; set; }
        public int Doc_Status { get; set; }
    
        public virtual ICollection<clase> clase { get; set; }
    }
}
