//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public docente()
        {
            this.docente_clase = new HashSet<docente_clase>();
            this.materia_clase = new HashSet<materia_clase>();
        }
    
        public long Doc_ID { get; set; }
        public string Doc_Doc { get; set; }
        public string Doc_Nom { get; set; }
        public string Doc_Apel { get; set; }
        public string Doc_Tel { get; set; }
        public string Doc_Email { get; set; }
        public string Doc_Passw { get; set; }
        public System.DateTime Doc_FecReg { get; set; }
        public int Doc_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<docente_clase> docente_clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materia_clase> materia_clase { get; set; }
    }
}
