//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia_clase
    {
        public long Macl_ID { get; set; }
        public long Clas_ID { get; set; }
        public long Mat_ID { get; set; }
        public long Doc_ID { get; set; }
    
        public virtual clase clase { get; set; }
        public virtual materia materia { get; set; }
    }
}
