//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodo
    {
        public periodo()
        {
            this.alumno_clase = new HashSet<alumno_clase>();
            this.clase = new HashSet<clase>();
        }
    
        public long Per_ID { get; set; }
        public string Per_Nom { get; set; }
        public System.DateTime Per_Ini { get; set; }
        public System.DateTime Per_Fin { get; set; }
    
        public virtual ICollection<alumno_clase> alumno_clase { get; set; }
        public virtual ICollection<clase> clase { get; set; }
    }
}
